# Netlify Configuration for Gema Events Frontend
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command
  command = "npm run build"

  # Output directory (where Vite outputs the build)
  publish = "dist"

  # Node.js version to use for builds
  # Must match the version specified in package.json
  [build.environment]
    NODE_VERSION = "22"
    NPM_VERSION = "8"
    NODE_ENV = "production"

# Production context settings
[context.production]
  command = "npm run build"

  [context.production.environment]
    NODE_ENV = "production"

# Deploy Preview context (for pull requests)
[context.deploy-preview]
  command = "npm run build"

  [context.deploy-preview.environment]
    NODE_ENV = "production"

# Branch Deploy context
[context.branch-deploy]
  command = "npm run build"

# Redirect rules for Single Page Application
# This ensures all routes are handled by React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

  # Don't apply this redirect to API calls
  conditions = {Role = ["*"]}

# Redirect API calls to backend (if needed)
# Uncomment and update if you want Netlify to proxy API requests
# [[redirects]]
#   from = "/api/*"
#   to = "https://gema-project.onrender.com/api/:splat"
#   status = 200
#   force = true
#   headers = {X-From = "Netlify"}

# Security headers
[[headers]]
  for = "/*"

  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://unpkg.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com;
      img-src 'self' data: https: blob:;
      font-src 'self' data: https://fonts.gstatic.com;
      connect-src 'self' https://gema-project.onrender.com https://*.cloudinary.com https://*.stripe.com;
      frame-src 'self' https://*.stripe.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """

# Cache static assets
[[headers]]
  for = "/assets/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache JavaScript chunks
[[headers]]
  for = "/js/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS files
[[headers]]
  for = "/css/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache index.html (to ensure updates are immediately available)
[[headers]]
  for = "/index.html"

  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# PWA manifest
[[headers]]
  for = "/manifest.json"

  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

# Service Worker
[[headers]]
  for = "/sw.js"

  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # Optional: Lighthouse plugin for performance monitoring
  # Uncomment to enable performance audits on each deploy
  # [plugins.inputs.thresholds]
  #   performance = 0.8
  #   accessibility = 0.9
  #   best-practices = 0.9
  #   seo = 0.9
  #   pwa = 0.8

# Functions configuration (if you decide to add Netlify Functions later)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Build plugin settings
[build.processing]
  skip_processing = false

# Image optimization
[build.processing.images]
  compress = true

# CSS optimization
[build.processing.css]
  bundle = true
  minify = true

# JS optimization
[build.processing.js]
  bundle = true
  minify = true

# Form handling (if you add Netlify Forms)
# [build]
#   functions = "netlify/functions"

# Environment variables
# Note: Actual values should be set in Netlify dashboard
# This is just documentation of required variables
# Required environment variables:
# - VITE_API_BASE_URL
# - VITE_STRIPE_PUBLISHABLE_KEY
# - VITE_CLOUDINARY_CLOUD_NAME
# - VITE_CLOUDINARY_UPLOAD_PRESET
# - VITE_FIREBASE_API_KEY
# - VITE_FIREBASE_AUTH_DOMAIN
# - VITE_FIREBASE_PROJECT_ID
# - VITE_FIREBASE_STORAGE_BUCKET
# - VITE_FIREBASE_MESSAGING_SENDER_ID
# - VITE_FIREBASE_APP_ID
# See .env.example for complete list
